import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ── Obsidian Intellect Design System — Stitch tokens ───────────────
        'surface': '#11131b',
        'surface-dim': '#11131b',
        'surface-bright': '#373942',
        'surface-container-lowest': '#0c0e16',
        'surface-container-low': '#1a1b23',
        'surface-container': '#1e1f27',
        'surface-container-high': '#282932',
        'surface-container-highest': '#33343d',
        'on-surface': '#e2e1ed',
        'on-surface-variant': '#c4c7c8',
        'inverse-surface': '#e2e1ed',
        'inverse-on-surface': '#2f3039',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'surface-tint': '#c6c6c7',
        'primary': '#ffffff',
        'on-primary': '#2f3131',
        'primary-container': '#e2e2e2',
        'on-primary-container': '#636565',
        'inverse-primary': '#5d5f5f',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c7',
        'on-primary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#454747',
        'secondary': '#a4cbeb',
        'on-secondary': '#01344e',
        'secondary-container': '#214a66',
        'on-secondary-container': '#93bad9',
        'secondary-fixed': '#cae6ff',
        'secondary-fixed-dim': '#a4cbeb',
        'on-secondary-fixed': '#001e2f',
        'on-secondary-fixed-variant': '#214a66',
        'tertiary': '#ffffff',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#e2e2e2',
        'on-tertiary-container': '#636565',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#11131b',
        'on-background': '#e2e1ed',
        'surface-variant': '#33343d',
        // ── Brand accent ────────────────────────────────────────────────────
        'accent': '#C7A36A',
        'solar': '#FFBF00',
        // ── Console Design System — Architectural Editorial (Stitch) ────────
        'console-bg': '#11131b',
        'console-surface': '#171717',
        'console-border': 'rgba(255,255,255,0.05)',
        'text-primary': '#F5F5F5',
        'sys-text': '#A1A1A1',
        'tracking-accent': '#C7A36A',
        'align-green': '#779165',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      screens: {
        'xs': '375px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1440px',
        '2xl': '2560px',
      },
      spacing: {
        'unit': '4px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-tablet': '32px',
        'margin-desktop': 'clamp(32px, 5vw, 64px)',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        // ── Console fonts ──────────────────────────────────────────────────
        'geist': ['Geist', 'Inter', 'sans-serif'],
        'geist-mono': ['"Geist Mono"', '"JetBrains Mono"', 'monospace'],
        // ── Landing page display font ──────────────────────────────────────
        'display-lg': ['"Instrument Serif"', 'serif'],
        'display-md': ['"Instrument Serif"', 'serif'],
        // ── Shared UI fonts ────────────────────────────────────────────────
        'headline-lg': ['Geist', 'Inter', 'sans-serif'],
        'body-lg': ['Geist', 'Inter', 'sans-serif'],
        'body-md': ['Geist', 'Inter', 'sans-serif'],
        'label-sm': ['Geist', 'Inter', 'sans-serif'],
        'mono': ['"Geist Mono"', '"JetBrains Mono"', 'monospace'],
        'serif': ['"Instrument Serif"', 'serif'],
        'sans': ['Geist', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-md': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      backdropBlur: {
        'xs': '4px',
      },
      animation: {
        'fade-rise': 'fadeRise 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-rise-delay': 'fadeRise 1.2s cubic-bezier(0.16, 1, 0.3, 1) 0.3s forwards',
        'fade-rise-delay-2': 'fadeRise 1.2s cubic-bezier(0.16, 1, 0.3, 1) 0.6s forwards',
      },
      keyframes: {
        fadeRise: {
          'from': { opacity: '0', transform: 'translateY(24px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
